version: '4'
services:
  mysql_resource:
    image: mysql:latest
    container_name: mysql_auth
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
