version: '4'

services:
  mysql_reservation:
    image: mysql:latest
    container_name: mysql_accomodation
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


